sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.6-dev"
    - python: "3.7-dev"
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libasound2-dev python3-tk
  - sudo modprobe snd-dummy
install:
  - pip install -r requirements.txt
  - pip install -U coveralls flake8 pytest
language: python
script:
  - coverage run -m pytest
  - flake8 src
after_success: coveralls
