sudo: false
matrix:
    fast_finish: true
    include:
        - python: "3.4.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.6-dev"
          env: TOXENV=py36
cache:
  directories:
      - $HOME/.cache/pip
install:
    - pip install -r requirements.txt
    - pip install -U coveralls flake8 pytest
language: python
script:
    - coverage run -m pytest
    - flake8
after_success: coveralls
